In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [ ]:
# Here we are going to remove the training set and test set, since it is having the cross validation

#split into training set and test
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [ ]:
# Also we are going to remove this standardscaler

#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [8]:
from sklearn.model_selection import GridSearchCV

#from sklearn.tree import DecisionTreeRegressor

param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson',],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)


# fitting the model for grid search, 
#here we are going to remove this x-train and y-train, since we are using the grid search

grid.fit(indep, dep)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [9]:
# print best parameter after tuning
#print(grid.best_params_)

re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.095341,0.003609,0.008195,0.000748,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.833999,0.756119,0.830580,0.799088,0.825080,0.808973,0.029134,16
1,0.813096,0.004314,0.030781,0.002711,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856057,0.780110,0.863447,0.830081,0.843270,0.834593,0.029520,2
2,0.088744,0.002314,0.008196,0.000748,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.830818,0.779407,0.846232,0.813358,0.826131,0.819189,0.022500,10
3,0.806900,0.005568,0.029983,0.001095,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856408,0.780585,0.864001,0.831728,0.844243,0.835393,0.029515,1
4,0.236652,0.005151,0.007596,0.001199,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.833642,0.763403,0.846874,0.815617,0.824316,0.816770,0.028626,12
5,2.288583,0.015144,0.027584,0.000490,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.855235,0.781713,0.855807,0.828540,0.841959,0.832651,0.027366,7
6,0.237652,0.006819,0.007395,0.000490,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.841705,0.771791,0.844067,0.809568,0.833703,0.820167,0.027096,9
7,2.311569,0.041060,0.028383,0.001019,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.853735,0.779338,0.861239,0.826787,0.845510,0.833322,0.029331,3
8,0.085147,0.000748,0.007196,0.000400,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.826968,0.741800,0.839584,0.805981,0.835353,0.809937,0.035981,14
9,0.822889,0.013520,0.028783,0.001326,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.855190,0.779364,0.865796,0.824811,0.838176,0.832667,0.030127,6
10,0.087145,0.002038,0.007596,0.001019,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.837935,0.750511,0.826703,0.804528,0.840628,0.812061,0.033302,13
11,0.815495,0.004333,0.030782,0.002711,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858202,0.777340,0.858616,0.825597,0.840841,0.832119,0.030006,8
12,0.095940,0.001265,0.007796,0.000748,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.833863,0.756171,0.825827,0.812496,0.820997,0.809871,0.027729,15
13,0.904840,0.006942,0.029982,0.001672,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860027,0.774850,0.863325,0.828720,0.838706,0.833126,0.031882,4
14,0.094940,0.001413,0.007796,0.000748,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.849954,0.773154,0.846919,0.807065,0.814099,0.818238,0.028295,11
15,0.841278,0.075602,0.024985,0.004896,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857196,0.778730,0.859391,0.828222,0.840239,0.832756,0.029333,5

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:33
BMI:43
Children:1
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[41259.2335752]

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(