In [1]:
# pandas is a library which holds many functions in it, 
  # and by using the import pandas we can load all the functions in it to this file.
   # Here we have mentioned pandas in shortform as pd. As of now here pandas is a table.

import pandas as pd

In [2]:
# Here dataset is assigned as a variable for the available given CSV.
  # pd->class,read_csv-Inside this we are calling the function.

# We should make sure that the csv file is available in the same location, 
  # or else it will give us error "file not found"

dataset=pd.read_csv("Salary_Data.csv")

In [3]:
# Here we are going to check what is available inside the dataset, 
 # it can also be executed(run)using print()

dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
# It displayed us all the data available in the excel sheet(csv).

In [4]:
# Here we are going to assign the Independent(Input)variable
# We are using a new logic how to get a separate column, and assign it to a variable.
# (Oru table la Yentha cloumn venumo, athai mattum thaniyea epadi oru variable la assign panrathu)
# (Enga namba Years of expericence -> Input variable uhh eduka poram)

independent=dataset[["YearsExperience"]]

In [5]:
# Here we are going to check what it available inside the independent variable(Input variable)

independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [ ]:
# It displays the Input variables(Years of experience) which are available inside the independent

In [6]:
# Here we are going to assign the dependent(Output)variable
# Here also, are using that above logic how to get a separate column, and assign it to a variable.
# (Oru table la Yentha cloumn venumo, athai mattum thaniyea epadi oru variable la assign panrathu)
# (Enga namba Salary -> Output variable uhh eduka poram)


dependent=dataset[["Salary"]]

In [7]:
# Here we are going to check what it available inside the dependent variable(Output variable)

dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [ ]:
# It displays the Output variables(Salary) which are available inside the dependent 

# HERE, we got both INDEPENDENT(I/P) & DEPENDENT(O/P) SEPARATELY.

# SO IN THE MODEL CREATION STEP->INPUT & OUTPUT SPLIT IS COMPLETED.

# NEXT STEP WE NEED TO PROCEED WITH SEPARATING THE TRAINING SET AND THE TEST SET.

In [8]:
# We use "Sklearn" library for this training set and test set.

# In the starting of this code we had used "Pandas". 
# It stores all the function which are inside the "Pandas in this file memory,
#  (such that memory consumption will be very high)".

# But here the memory consumption will be low, 
#   because here we are going to call only the needed function.

# This(.)means function->Kulla->function->kulla->Irukara function uhh call panrathu 
                        #OR
# Class->kulla->Class->kulla->Irukara class or function uhh call panrathu.

# Next: we are going to call the functions which we have imported(train_test_split).
# Then we are going to pass the parameters for it(independent->I/P, dependent->O/P,test size)

    
    
from sklearn.model_selection import train_test_split
train_test_split(independent, dependent, test_size=0.30,random_state=0)

[    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,
     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0
 17              5.3,
       Salary
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,
       Salary
 2    37731.0
 28  122391.0
 13   57081.0
 10   63218.0
 26  116969.0
 24  109431.0
 27  112635.0
 11   55794.0
 17   83088.0]

In [ ]:
# we got the above O/P, while exectuing the previous command,
# It denotes that we should add the variables for the INPUT/OUTPUT set.

In [9]:
# Here we have assigned the variables as (X_train,X_test,y_train,y_test=train_test_split)

# X->Input(X_train,X_test) and Y->Output(y_train,y_test)

# We know that we should not use the(Space) for naming the variables so we are using underscore(_).

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [ ]:
# As of now we have completed splitting the training set and test set, 
# Next we shall move to the model creation.

In [10]:
# Here we are going to see how we are going to use the"LINEAR REGRESSION".

# "SKLEARN" -> only provides most of the Machine learing Algorithm.

# We should make sure that format (from sklearn.linear_model import LinearRegression),
   # is correct without any spelling mistake, then only it will call the fun properly.

# We should create a variable "regressor", 
   # most of the top companies are using this "regressor" variable only for LinearRegression.

# regressor=LinearRegression(), Here this "LinearRegression()" is considered as a class, 
  # all the functions inside this class will be assigned to the "regressor variable".
    
# Then we are going to call the "fit function which is inside the regressor"(regressor.fit)

# We know that it is a model, to make this model to learn we need to pass the "I/P and O/P"
  # (entha model uhh padika veikaa inputs forward pannanum).
    
    # X_train --> Training set's I/P.
    # Y_train --> Training set's O/P.
    
  # from sklearn.linear_model import LinearRegression
  # regressor=LinearRegression()
    # the above 2 lines are just the procedure or formula.
    
  # we need to substitute this using the "fit function or method", using the "(X_train,y_train)",
     # After the execution of this line -->"regressor.fit(X_train,y_train)", 
       # weight and bias would have been calculated.
        # fit method or function-->executed means -->model has been created
         # (that means respective constant values yellamey 
            # dataset ku etha mari create agidichi nu artham)
    
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [ ]:
# The above 3 line of codes are for the "Learning Phase".

# We know that -->LinearRegression()-->Model created,
  # LinearRegression means ---->"(Slope/Weight) & Bias/Intercept", 
    # we will be eager to find its values, 
     # so for that we should use the below code 
     # weight=regressor.coef_ 
     # weight

In [11]:
weight=regressor.coef_
weight

array([[9360.26128619]])

In [ ]:
# This is the "Weight or Slope" for this model (array([[9360.26128619]]))
   # Next prediction ku anna hook(hint)

# Next we should find the Bais, for that we should use the below code,
  # bais=regressor.intercept_
  # bais

In [12]:
bais=regressor.intercept_
bais

array([26777.3913412])

In [ ]:
# Namboloda ---> "Model & Weight & Bais & formula" all will be stored in,
  # regressor.fit(X_train,y_train)  in this regressor.
    
# We have created the Model.
  # And Found "Weight & bais".

# So, Next step is ---> "EVALUATION METRICS",
  # To check whether our model has came correct,
     # (namba model correct uhh vanthu iruka na check panrathu )

In [ ]:
# So, once the previous step has been completed,

   # y_pred    ---> we are going to create a variable
   # regressor ---> everything will be already saved in it (ellamey save agi irukum)
   # predict   ---> application-->kana-->function (end goal of AI is prediction)
   # (X_test)  ---> evaluation metrics should be done for the test data only,
                    #(since: (Y_test--> Actual data))

In [13]:
y_pred=regressor.predict(X_test)

In [ ]:
# y_pred=regressor.predict(X_test) if we execute this,
  
    # I/P(X_test)-->Oda test ellam, namba learning kulla poitu,
     #(This is the place for "Cross checking",)Ethu than namba cross check panrathuku ana process,
        #Namba brain prediction panna "Output",
        #Yedutku --> Test Data
        # Yean na-->Test Data oda yentha value um mey training set oda include agala
     
    #So for cross checking we have found the prediction like this,
      # Ethai cross check panna: y_pred=regressor.predict(X_test),
         # prediction na entha mari kandu pidichi vachi irukom.

 # Next we need to find the "R2_score value"

In [ ]:
# This is the function for "R2_score",
   # from sklearn.metrics import r2_score
    
    # We are going to create a variable "r_score" and pass "r2_score" in it, 
      # with the parameters
        # y_test ---> Actual O/P
        # y_pred ---> predicted

In [14]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [ ]:
# Next going to find the "r_score" value by executing this.

In [15]:
r_score

0.9740993407213511

In [ ]:
# We found the"r_score" value = "0.9740993407213511",
  # We already know the concept of r_score, 
    # it will be (0 or 1), if it is near to 1, then it is a good model, 
     # so from our "r_score" value, 
        # we came to know that our model is a good model and it has learnt well.

In [16]:
# To save the model here we use "pickle function"
 # We are going to creat a dummy filename (filename) for our finalized model.
    # If it is our finalized model, we can put it as,
     # "finalized_model_linear.sav"
        # if we are using many algorithm, we need to mention that algorithm name(linear)
         # .sav ---> is used for saving the pickle -->extension

import pickle
filename="finalized_model_linear.sav"

In [ ]:
# If the above code is executed it moves to the next line,
 # since only file name is created,
    # we need to assign the model to the file name.

In [ ]:
# for assigning the model we need to use this code,
 # pickle.dump(regressor,open(filename,'wb'))
    # regressor ---> it holds everything in it
    # wb        ---> Write binary

In [17]:
pickle.dump(regressor,open(filename,'wb'))

In [ ]:
# If we run the above code (pickle.dump(regressor,open(filename,'wb'))), 
  #it will be saved and also it will create a new folder
   # like this "finalized_model_linear.sav",
    # we need to save our model like this only,
     # Such that while creating an End user-->application, we can work hassle free.

 # So, Successfully we have saved our model,
  # Next: We need to load our saved model and check whether it is working correctly.
    # Such that we can send it to the next ---> Phase-2 (Deployment/End user application creation)

In [ ]:
# If we run this code --> (loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')))
  # this whole model will be loaded and saved under this "loaded_model-->variable"
    # rb ---> read binary
    
 # Next we use: result=loaded_model.predict([[15]]) 
  # For example: If we need to predict the 15 years of experience we can use 15.

In [18]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[15]])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
# After we execute the above code, it just displays the above warning message, we can ignore it.

In [19]:
result

array([[167181.3106341]])

In [ ]:
# Then once we execute this "result", it predicts the output for 15 experience.

# So, save panna model--->load pani-->Antha load panna model mulaima-->predict pani irukom.

#Such that, we can confirm that the entire model is working perfectly.
  # We have evaluated it also.